#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for events package
#
# IDENTIFICATION
#    src/backend/pipeline/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/pipeline
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = decode.o merge.o stream.o streambuf.o

include $(top_srcdir)/src/backend/common.mk
