#! /usr/bin/python

import getopt
import psycopg2
import os

"""
Event (F)
    Byte1('E')
        Identifies the message as an event.
    Int32(8)
        Length of message contents in bytes, including self.
    String
        Specifies the decoder to decode the payload with
    Int32
        Specifies the number of bytes in the raw payload
    ByteN
        Raw payload
"""


def main():
    conn_str = "host='localhost' dbname='derek' user='derek'"
    conn = psycopg2.connect(conn_str)
    import pdb; pdb.set_trace()
    


if __name__ == '__main__':
    """Accept JSON payload and emit raw to postgres process"""
    main()
