#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for locator and data distribution
#
# Copyright(C) 2010-2012 Postgres-XC Development Group
#
# IDENTIFICATION
#    $PostgreSQL$
#
#-------------------------------------------------------------------------

subdir = src/backend/pgxc/locator
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = locator.o redistrib.o

include $(top_srcdir)/src/backend/common.mk
