#-------------------------------------------------------------------------
#
# Makefile for src/test
#
# Portions Copyright (c) 1994, Regents of the University of California
# Portions Copyright (c) 2013-2015, PipelineDB
#
# src/test/Makefile
#
#-------------------------------------------------------------------------

subdir = src/test
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = regress isolation py unit

$(recurse)
