#! /usr/bin/python

import argparse
import getpass
import subprocess


HOST = 'localhost'
PORT = '5432'
USER = getpass.getuser()
DB_NAME = USER


def main(args):
    encoding = args.encoding
    stream = args.stream
    subprocess.call(['./emit', HOST, PORT, USER, DB_NAME, encoding, stream])


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--stream', action='store', dest='stream', required=True,
                        help='Stream to emit to')
    parser.add_argument('--encoding', dest='encoding', required=True,
                        action='store', help='Encoding of the events being emitted')
    args = parser.parse_args()
    main(args)