#! /usr/bin/python

import argparse
import getpass
import random
import simplejson
import string
import subprocess
import sys


def main(args, keys):
    count = 0
    while args.n is None or (count < args.n):
        d = {}
        for k in keys:
            field_type = getattr(globals()['__builtins__'], getattr(args, k))
            value = None
            if field_type == str:
                value = ''.join([random.choice(string.hexdigits) for _ in range(random.randint(1, 32))])
            else:
                value = field_type(random.random() * (random.randint(1, 1024)))
            d[k] = value
        count += 1
        print simplejson.dumps(d)


if __name__ == '__main__':
    """
    Generates random JSON data using the specified key names and types
    
    Ex:
    
    generate-json --key=str --value=int --n=2
    {'value': 477, 'key': '4cFaD78Cf2EFF9Afef9C75EaAB'}
    {'value': 4, 'key': 'f'}
    """
    parser = argparse.ArgumentParser()
    parser.add_argument('--n', action='store', dest='n', type=int, required=False,
                        help='Number of events to generate')
    keys = []
    for arg in sys.argv[1:]:
        if arg.startswith('--') and '=' in arg:
            k, v = arg.split('=')
            if k == '--n': continue
            if k[2:] in keys:
                print 'Duplicate field name %s' % k
                sys.exit(1)
            parser.add_argument(k, action='store', dest=k[2:], choices=('int', 'str', 'float'))
            keys.append(k[2:])
            
    args = parser.parse_args()
    main(args, keys)