#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for barrier
#
#  Portions Copyright (c) 2010-2012 Postgres-XC Development Group
#
# IDENTIFICATION
#    $PostgreSQL$
#
#-------------------------------------------------------------------------

subdir = src/backend/pgxc/barrier
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = barrier.o

include $(top_srcdir)/src/backend/common.mk
