.TH "rmtemplate_gis" "1" "" "Roberto Boati" "Postgis utilities"
.SH "NAME"
.LP 
rmtemplate_gis \- Delete Postgis template in a PostgreSQL server.
.SH "SYNTAX"
.LP 
rmtemplate_gis [\fIoption\fP]
.SH "DESCRIPTION"
.LP 
This program deletes a template database Postgis.
.br 
It requires to be run by root, or by PostgreSQL superuser (postgres), 
or by a dba, or by the cluster owner, or by the database owner.
.br 
PostgreSQL should be running.
.SH "OPTIONS"
.LP
.TP
For default values see below.
.TP 
\fB\-\-template=\fR<\fItemplatedb\fP>
Set template name to be <\fItemplatedb\fP>
.TP
Envirunment variable: \fITEMPLATEDB\fR.
.TP 
\fB\-\-dba=\fR<\fIdba_name\fP>
DBA is required to perform template database building.
.TP
Envirunment variable: \fIDBAUSER\fR.
.TP 
\fB\-\-help\fR
Output help information and exit.
.SH "ENVIRONMENT"
.TP 
.B TEMPLATEDB
If
.RB $ TEMPLATEDB
is set, its value is used as the default template name.
.TP 
.B DBAUSER
If
.RB $ DBAUSER
is set, its value is used as the default DBA for removing the template.
.SH "FILES"
.LP
The environment variables for template_gis creation, removal and usage may be stored in files, as follows:
.TP
.B /etc/default/postgis
will designate default values for the whole system.
.TP
.B $HOME/.postgis/profile
will designate the values used by the current user by default.
Beware, this is the current SYSTEM user, not the dba or the database owner to 
become. As those values are more user specific, they supersede the ones in the 
system default file for the current user.
.SH "NOTES"
.LP
The order of precedence of the variables definition:
.TP
.B 1.
Command line options.
.TP
.B 2.
Environment variables.
.TP
.B 3.
The user specific profile file.
.TP
.B 4.
The system wide default file.
.TP
.B The builtin (hardwired) values are not a good choice.
.SH "EXAMPLES"
.LP 
To run this program the standard way, you can simply type:
.LP 
# \fBrmtemplate\_gis\fR
.LP 
Alternatively you can specify also a template name to delete:
.LP 
# \fBrmtemplate\_gis \-\-template=template\_postgis\fR
.SH "AUTHORS"
.LP 
Alex Bodnaru <alexbodn@012.net.il>
.br 
Roberto Boati <roberto.boati@gmail.com>
.SH "SEE ALSO"
.LP 
createdb.postgis(1), mktemplate_gis(1)
