#! /bin/bash

INSTALL_PREFIX=/usr/local/lib/pipelinedb

ln -s $INSTALL_PREFIX/bin/pipelinedb /usr/local/bin/pipelinedb
ln -s $INSTALL_PREFIX/bin/pipelinedb-debug /usr/local/bin/pipelinedb-debug
ln -s $INSTALL_PREFIX/bin/pipeline-ctl /usr/local/bin/pipeline-ctl
ln -s $INSTALL_PREFIX/bin/pipeline-ctl /usr/local/bin/pg_ctl
ln -s $INSTALL_PREFIX/bin/pipeline-init /usr/local/bin/pipeline-init
ln -s $INSTALL_PREFIX/bin/psql /usr/local/bin/psql
ln -s $INSTALL_PREFIX/bin/psql /usr/local/bin/pipeline
ln -s $INSTALL_PREFIX/bin/pipeline-config /usr/local/bin/pg_config
ln -s $INSTALL_PREFIX/bin/pipeline-dump /usr/local/bin/pipeline-dump
ln -s $INSTALL_PREFIX/bin/pipeline-dumpall /usr/local/bin/pipeline-dumpall
ln -s $INSTALL_PREFIX/bin/pipeline-restore /usr/local/bin/pipeline-restore

rm $INSTALL_PREFIX/postinst

echo "
    ____  _            ___            ____  ____
   / __ \(_)___  ___  / (_)___  ___  / __ \/ __ )
  / /_/ / / __ \/ _ \/ / / __ \/ _ \/ / / / __  |
 / ____/ / /_/ /  __/ / / / / /  __/ /_/ / /_/ /
/_/   /_/ .___/\___/_/_/_/ /_/\___/_____/_____/
       /_/

PipelineDB successfully installed. To get started, initialize a
database directory:

pipeline-init -D <data directory>

where <data directory> is a nonexistent directory where you'd
like all of your database files to live.

You can find the PipelineDB documentation at:

http://docs.pipelinedb.com
"
