#!/bin/bash

set -e

# check if the data directory is empty,
# if not, initialize it.
# if [ ! -d "/mnt/pipelinedb/data" ]; then
if [ ! "$(ls -A /mnt/pipelinedb/data)" ]; then
    mkdir -p /mnt/pipelinedb
    chmod 777 /mnt/pipelinedb
    su - pipeline -c "pipeline-init --encoding=UTF8 -D /mnt/pipelinedb/data"
    su - pipeline -c "pipeline-ctl -D /mnt/pipelinedb/data -w start"
    psql -U pipeline -c "ALTER USER pipeline PASSWORD 'pipeline'"
    su - pipeline -c "pipeline-ctl -D /mnt/pipelinedb/data -w stop"
    cp /scripts/conf/*.conf /mnt/pipelinedb/data/
fi

su - pipeline -c "pipeline-server -D /mnt/pipelinedb/data"
