#!/bin/sh

if [ -z "$TMPDIR" ]; then
	TMPDIR=/tmp
fi

OUTFILE="${TMPDIR}/regress_index_out_$$"

echo "Running GiST concurrency Regression."

DB=postgis_reg
PGDATABASE=$DB
export PGDATABASE

if [ "$1" = "prepare" ]; then
	echo ""
	echo "Index Creation will take some time..."
	echo ""

	createdb > /dev/null
	createlang plpgsql > /dev/null
	psql -f ../lwpostgis.sql > /dev/null 2>&1

	psql -f regress_lots_of_points.sql 
	psql -c "CREATE INDEX quick_gist on test using gist (the_geom)" 
else
if [ "$1" = "run" ]; then
	# Concurrent clients:
	psql -c "update test set num=-num WHERE the_geom && 'BOX3D(125 125,135 135)'::box3d"  &
	psql -c "update test set num=-num WHERE the_geom && 'BOX3D(125 125,135 135)'::box3d"  &
	psql -c "update test set num=-num WHERE the_geom && 'BOX3D(125 125,135 135)'::box3d"  &
	 
	wait
else
if [ "$1" = "drop" ]; then
	dropdb $DB > /dev/null
else
	echo "Usage: $0 [prepare|run|drop]"
fi
fi
fi

