#----------------------------------------------------------------------------
#
# Postgres-XC documentation tool makefile
#
# Copyright (c) 2010-2012 Postgres-XC Development Group
#
# doc-xc/Makefile
#
#----------------------------------------------------------------------------

subdir = src/pgxc
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = tools

$(recurse)
