#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for remote copy management
#
#  Copyright (c) 2010-2012 Postgres-XC Development Group
#
# IDENTIFICATION
#    $PostgreSQL$
#
#-------------------------------------------------------------------------

subdir = src/backend/pgxc/copy
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = copyops.o remotecopy.o

include $(top_srcdir)/src/backend/common.mk
