#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for events package
#
# IDENTIFICATION
#    src/backend/events/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/events
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = decoder.o delimited.o

include $(top_srcdir)/src/backend/common.mk
