AROPT = crs

DLSUFFIX = .so

ifdef PGXS
  BE_DLLLIBS = -bundle_loader $(bindir)/pipeline-server
else
  BE_DLLLIBS = -bundle_loader $(top_builddir)/src/backend/pipeline-server
endif

# Rule for building a shared library from a single .o file
%.so: %.o
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDFLAGS_SL) -bundle $(BE_DLLLIBS) -o $@ $<
