# Portions Copyright (c) 2013-2016, PipelineDB

AROPT = crs

DLSUFFIX = .so

PIPELINE_SERVER_BINARY = pipeline-server

ifdef PGXS
  BE_DLLLIBS = -bundle_loader $(bindir)/$(PIPELINE_SERVER_BINARY)
else
  BE_DLLLIBS = -bundle_loader $(top_builddir)/src/backend/$(PIPELINE_SERVER_BINARY)
endif

# Rule for building a shared library from a single .o file
%.so: %.o
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDFLAGS_SL) -bundle $(BE_DLLLIBS) -o $@ $<
