CREATE FOREIGN TABLE stream0 (id integer) SERVER pipelinedb;
SELECT schema, name, queries FROM pipelinedb.get_streams() ORDER BY name;
CREATE VIEW ps0 AS SELECT id FROM stream0;
SELECT schema, name, queries FROM pipelinedb.get_streams() ORDER BY name;
CREATE VIEW ps1 AS SELECT count(*) FROM stream0;
CREATE VIEW ps2 AS SELECT id FROM stream0;
CREATE FOREIGN TABLE stream1 (x integer, y timestamp) SERVER pipelinedb;
CREATE VIEW ps3 AS SELECT x, y FROM stream1;
SELECT schema, name, queries FROM pipelinedb.get_streams() ORDER BY name;
CREATE VIEW ps4 AS SELECT id::text FROM stream0;
SELECT schema, name, queries FROM pipelinedb.get_streams() ORDER BY name;
CREATE FOREIGN TABLE stream2 (x integer) SERVER pipelinedb;
SELECT schema, name, queries FROM pipelinedb.get_streams() ORDER BY name;
CREATE VIEW ps5 AS SELECT x FROM stream2;
SELECT schema, name, queries FROM pipelinedb.get_streams() ORDER BY name;
DROP VIEW ps0;
SELECT schema, name, queries FROM pipelinedb.get_streams() ORDER BY name;
DROP VIEW ps1;
SELECT schema, name, queries FROM pipelinedb.get_streams() ORDER BY name;
DROP VIEW ps2;
DROP VIEW ps3;
SELECT schema, name, queries FROM pipelinedb.get_streams() ORDER BY name;
DROP VIEW ps5;
SELECT schema, name, queries FROM pipelinedb.get_streams() ORDER BY name;
DROP FOREIGN TABLE stream2;
SELECT schema, name, queries FROM pipelinedb.get_streams() ORDER BY name;
DROP FOREIGN TABLE stream1;
DROP FOREIGN TABLE stream0 CASCADE;
SELECT schema, name, queries FROM pipelinedb.get_streams() ORDER BY name;
