CREATE CONTINUOUS VIEW test_numeric_to_int2 AS SELECT x::numeric FROM numeric_stream;
CREATE CONTINUOUS VIEW test_numeric_to_int4 AS SELECT x::numeric FROM numeric_stream;
CREATE CONTINUOUS VIEW test_numeric_to_float4 AS SELECT x::numeric FROM numeric_stream;
CREATE CONTINUOUS VIEW test_numeric_to_float8 AS SELECT x::numeric FROM numeric_stream;
CREATE CONTINUOUS VIEW test_money_to_numeric AS SELECT x::money FROM money_stream;
CREATE CONTINUOUS VIEW test_numeric_to_money AS SELECT x::numeric FROM numeric_stream;
CREATE CONTINUOUS VIEW test_int4_to_money AS SELECT x::int4 FROM int4_stream;
CREATE CONTINUOUS VIEW test_int8_to_money AS SELECT x::int8 FROM int8_stream;
CREATE CONTINUOUS VIEW test_int4_to_bool AS SELECT x::int4 FROM int4_stream;
CREATE CONTINUOUS VIEW test_bool_to_int4 AS SELECT x::bool FROM bool_stream;
CREATE CONTINUOUS VIEW test_int8_to_oid AS SELECT x::int8 FROM int8_stream;
CREATE CONTINUOUS VIEW test_int2_to_oid AS SELECT x::int2 FROM int2_stream;
CREATE CONTINUOUS VIEW test_int4_to_oid AS SELECT x::int4 FROM int4_stream;
CREATE CONTINUOUS VIEW test_oid_to_int8 AS SELECT x::oid FROM oid_stream;
CREATE CONTINUOUS VIEW test_oid_to_int4 AS SELECT x::oid FROM oid_stream;
CREATE CONTINUOUS VIEW test_oid_to_regproc AS SELECT x::oid FROM oid_stream;
CREATE CONTINUOUS VIEW test_int8_to_regproc AS SELECT x::int8 FROM int8_stream;
CREATE CONTINUOUS VIEW test_int2_to_regproc AS SELECT x::int2 FROM int2_stream;
CREATE CONTINUOUS VIEW test_int4_to_regproc AS SELECT x::int4 FROM int4_stream;
CREATE CONTINUOUS VIEW test_oid_to_regprocedure AS SELECT x::oid FROM oid_stream;
CREATE CONTINUOUS VIEW test_int8_to_regprocedure AS SELECT x::int8 FROM int8_stream;
CREATE CONTINUOUS VIEW test_int2_to_regprocedure AS SELECT x::int2 FROM int2_stream;
CREATE CONTINUOUS VIEW test_int4_to_regprocedure AS SELECT x::int4 FROM int4_stream;
CREATE CONTINUOUS VIEW test_oid_to_regoper AS SELECT x::oid FROM oid_stream;
CREATE CONTINUOUS VIEW test_int8_to_regoper AS SELECT x::int8 FROM int8_stream;

INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO numeric_stream (x) VALUES (1.00000001);
INSERT INTO numeric_stream (x) VALUES (1.00000001);
INSERT INTO numeric_stream (x) VALUES (1.00000001);
INSERT INTO numeric_stream (x) VALUES (1.00000001);
INSERT INTO numeric_stream (x) VALUES (1.00000001);
INSERT INTO money_stream (x) VALUES ('42.42');
INSERT INTO numeric_stream (x) VALUES (1.00000001);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO bool_stream (x) VALUES ('true');
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO oid_stream (x) VALUES (104);
INSERT INTO oid_stream (x) VALUES (104);
INSERT INTO oid_stream (x) VALUES (104);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO oid_stream (x) VALUES (104);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO oid_stream (x) VALUES (104);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO oid_stream (x) VALUES (104);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO oid_stream (x) VALUES (104);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO oid_stream (x) VALUES (104);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO oid_stream (x) VALUES (104);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO oid_stream (x) VALUES (104);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO int8_stream (x) VALUES (8);

SELECT x FROM test_numeric_to_int2;
SELECT x FROM test_numeric_to_int4;
SELECT x FROM test_numeric_to_float4;
SELECT x FROM test_numeric_to_float8;
SELECT x FROM test_money_to_numeric;
SELECT x FROM test_numeric_to_money;
SELECT x FROM test_int4_to_money;
SELECT x FROM test_int8_to_money;
SELECT x FROM test_int4_to_bool;
SELECT x FROM test_bool_to_int4;
SELECT x FROM test_int8_to_oid;
SELECT x FROM test_int2_to_oid;
SELECT x FROM test_int4_to_oid;
SELECT x FROM test_oid_to_int8;
SELECT x FROM test_oid_to_int4;
SELECT x FROM test_oid_to_regproc;
SELECT x FROM test_int8_to_regproc;
SELECT x FROM test_int2_to_regproc;
SELECT x FROM test_int4_to_regproc;
SELECT x FROM test_oid_to_regprocedure;
SELECT x FROM test_int8_to_regprocedure;
SELECT x FROM test_int2_to_regprocedure;
SELECT x FROM test_int4_to_regprocedure;
SELECT x FROM test_oid_to_regoper;
SELECT x FROM test_int8_to_regoper;

DROP CONTINUOUS VIEW test_numeric_to_int2;
DROP CONTINUOUS VIEW test_numeric_to_int4;
DROP CONTINUOUS VIEW test_numeric_to_float4;
DROP CONTINUOUS VIEW test_numeric_to_float8;
DROP CONTINUOUS VIEW test_money_to_numeric;
DROP CONTINUOUS VIEW test_numeric_to_money;
DROP CONTINUOUS VIEW test_int4_to_money;
DROP CONTINUOUS VIEW test_int8_to_money;
DROP CONTINUOUS VIEW test_int4_to_bool;
DROP CONTINUOUS VIEW test_bool_to_int4;
DROP CONTINUOUS VIEW test_int8_to_oid;
DROP CONTINUOUS VIEW test_int2_to_oid;
DROP CONTINUOUS VIEW test_int4_to_oid;
DROP CONTINUOUS VIEW test_oid_to_int8;
DROP CONTINUOUS VIEW test_oid_to_int4;
DROP CONTINUOUS VIEW test_oid_to_regproc;
DROP CONTINUOUS VIEW test_int8_to_regproc;
DROP CONTINUOUS VIEW test_int2_to_regproc;
DROP CONTINUOUS VIEW test_int4_to_regproc;
DROP CONTINUOUS VIEW test_oid_to_regprocedure;
DROP CONTINUOUS VIEW test_int8_to_regprocedure;
DROP CONTINUOUS VIEW test_int2_to_regprocedure;
DROP CONTINUOUS VIEW test_int4_to_regprocedure;
DROP CONTINUOUS VIEW test_oid_to_regoper;
DROP CONTINUOUS VIEW test_int8_to_regoper;
