CREATE CONTINUOUS VIEW test_int2_to_regoper AS SELECT x::int2 FROM int2_stream;
CREATE CONTINUOUS VIEW test_int4_to_regoper AS SELECT x::int4 FROM int4_stream;
CREATE CONTINUOUS VIEW test_oid_to_regoperator AS SELECT x::oid FROM oid_stream;
CREATE CONTINUOUS VIEW test_int8_to_regoperator AS SELECT x::int8 FROM int8_stream;
CREATE CONTINUOUS VIEW test_int2_to_regoperator AS SELECT x::int2 FROM int2_stream;
CREATE CONTINUOUS VIEW test_int4_to_regoperator AS SELECT x::int4 FROM int4_stream;
CREATE CONTINUOUS VIEW test_oid_to_regclass AS SELECT x::oid FROM oid_stream;
CREATE CONTINUOUS VIEW test_int8_to_regclass AS SELECT x::int8 FROM int8_stream;
CREATE CONTINUOUS VIEW test_int2_to_regclass AS SELECT x::int2 FROM int2_stream;
CREATE CONTINUOUS VIEW test_int4_to_regclass AS SELECT x::int4 FROM int4_stream;
CREATE CONTINUOUS VIEW test_oid_to_regtype AS SELECT x::oid FROM oid_stream;
CREATE CONTINUOUS VIEW test_int8_to_regtype AS SELECT x::int8 FROM int8_stream;
CREATE CONTINUOUS VIEW test_int2_to_regtype AS SELECT x::int2 FROM int2_stream;
CREATE CONTINUOUS VIEW test_int4_to_regtype AS SELECT x::int4 FROM int4_stream;
CREATE CONTINUOUS VIEW test_oid_to_regconfig AS SELECT x::oid FROM oid_stream;
CREATE CONTINUOUS VIEW test_int8_to_regconfig AS SELECT x::int8 FROM int8_stream;
CREATE CONTINUOUS VIEW test_int2_to_regconfig AS SELECT x::int2 FROM int2_stream;
CREATE CONTINUOUS VIEW test_int4_to_regconfig AS SELECT x::int4 FROM int4_stream;
CREATE CONTINUOUS VIEW test_oid_to_regdictionary AS SELECT x::oid FROM oid_stream;
CREATE CONTINUOUS VIEW test_int8_to_regdictionary AS SELECT x::int8 FROM int8_stream;
CREATE CONTINUOUS VIEW test_int2_to_regdictionary AS SELECT x::int2 FROM int2_stream;
CREATE CONTINUOUS VIEW test_int4_to_regdictionary AS SELECT x::int4 FROM int4_stream;
CREATE CONTINUOUS VIEW test_text_to_regclass AS SELECT x::text FROM text_stream;
CREATE CONTINUOUS VIEW test_varchar_to_regclass AS SELECT x::varchar FROM varchar_stream;
CREATE CONTINUOUS VIEW test_text_to_bpchar AS SELECT x::text FROM text_stream;
CREATE CONTINUOUS VIEW test_text_to_varchar AS SELECT x::text FROM text_stream;
CREATE CONTINUOUS VIEW test_varchar_to_text AS SELECT x::varchar FROM varchar_stream;
CREATE CONTINUOUS VIEW test_varchar_to_bpchar AS SELECT x::varchar FROM varchar_stream;
CREATE CONTINUOUS VIEW test_char_to_text AS SELECT x::char FROM char_stream;

INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO int4_stream (x) VALUES (4);
INSERT INTO int4_stream (x) VALUES (4);
INSERT INTO int4_stream (x) VALUES (4);
INSERT INTO int4_stream (x) VALUES (4);
INSERT INTO int4_stream (x) VALUES (4);
INSERT INTO int4_stream (x) VALUES (4);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int4_stream (x) VALUES (4);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO int4_stream (x) VALUES (4);
INSERT INTO oid_stream (x) VALUES (104);
INSERT INTO oid_stream (x) VALUES (104);
INSERT INTO oid_stream (x) VALUES (104);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO int4_stream (x) VALUES (4);
INSERT INTO oid_stream (x) VALUES (104);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO int4_stream (x) VALUES (4);
INSERT INTO oid_stream (x) VALUES (104);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO int4_stream (x) VALUES (4);
INSERT INTO oid_stream (x) VALUES (104);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO int4_stream (x) VALUES (4);
INSERT INTO oid_stream (x) VALUES (104);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO int4_stream (x) VALUES (4);
INSERT INTO oid_stream (x) VALUES (104);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO int4_stream (x) VALUES (4);
INSERT INTO oid_stream (x) VALUES (104);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO int4_stream (x) VALUES (4);
INSERT INTO oid_stream (x) VALUES (104);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int2_stream (x) VALUES (2);
INSERT INTO int4_stream (x) VALUES (4);
INSERT INTO text_stream (x) VALUES ('text text text!');
INSERT INTO varchar_stream (x) VALUES ('varchaaaaaaaar');
INSERT INTO text_stream (x) VALUES ('text text text!');
INSERT INTO text_stream (x) VALUES ('text text text!');
INSERT INTO varchar_stream (x) VALUES ('varchaaaaaaaar');
INSERT INTO varchar_stream (x) VALUES ('varchaaaaaaaar');
INSERT INTO char_stream (x) VALUES ('c');
INSERT INTO char_stream (x) VALUES ('c');
INSERT INTO char_stream (x) VALUES ('c');
INSERT INTO text_stream (x) VALUES ('text text text!');
INSERT INTO varchar_stream (x) VALUES ('varchaaaaaaaar');
INSERT INTO text_stream (x) VALUES ('text text text!');
INSERT INTO varchar_stream (x) VALUES ('varchaaaaaaaar');
INSERT INTO char_stream (x) VALUES ('c');
INSERT INTO int4_stream (x) VALUES (4);
INSERT INTO int4_stream (x) VALUES (4);
INSERT INTO int4_stream (x) VALUES (4);
INSERT INTO int8_stream (x) VALUES (8);
INSERT INTO int4_stream (x) VALUES (4);
INSERT INTO text_stream (x) VALUES ('text text text!');
INSERT INTO varchar_stream (x) VALUES ('varchaaaaaaaar');

SELECT x FROM test_int2_to_regoper;
SELECT x FROM test_int4_to_regoper;
SELECT x FROM test_oid_to_regoperator;
SELECT x FROM test_int8_to_regoperator;
SELECT x FROM test_int2_to_regoperator;
SELECT x FROM test_int4_to_regoperator;
SELECT x FROM test_oid_to_regclass;
SELECT x FROM test_int8_to_regclass;
SELECT x FROM test_int2_to_regclass;
SELECT x FROM test_int4_to_regclass;
SELECT x FROM test_oid_to_regtype;
SELECT x FROM test_int8_to_regtype;
SELECT x FROM test_int2_to_regtype;
SELECT x FROM test_int4_to_regtype;
SELECT x FROM test_oid_to_regconfig;
SELECT x FROM test_int8_to_regconfig;
SELECT x FROM test_int2_to_regconfig;
SELECT x FROM test_int4_to_regconfig;
SELECT x FROM test_oid_to_regdictionary;
SELECT x FROM test_int8_to_regdictionary;
SELECT x FROM test_int2_to_regdictionary;
SELECT x FROM test_int4_to_regdictionary;
SELECT x FROM test_text_to_regclass;
SELECT x FROM test_varchar_to_regclass;
SELECT x FROM test_text_to_bpchar;
SELECT x FROM test_text_to_varchar;
SELECT x FROM test_varchar_to_text;
SELECT x FROM test_varchar_to_bpchar;
SELECT x FROM test_char_to_text;

DROP CONTINUOUS VIEW test_int2_to_regoper;
DROP CONTINUOUS VIEW test_int4_to_regoper;
DROP CONTINUOUS VIEW test_oid_to_regoperator;
DROP CONTINUOUS VIEW test_int8_to_regoperator;
DROP CONTINUOUS VIEW test_int2_to_regoperator;
DROP CONTINUOUS VIEW test_int4_to_regoperator;
DROP CONTINUOUS VIEW test_oid_to_regclass;
DROP CONTINUOUS VIEW test_int8_to_regclass;
DROP CONTINUOUS VIEW test_int2_to_regclass;
DROP CONTINUOUS VIEW test_int4_to_regclass;
DROP CONTINUOUS VIEW test_oid_to_regtype;
DROP CONTINUOUS VIEW test_int8_to_regtype;
DROP CONTINUOUS VIEW test_int2_to_regtype;
DROP CONTINUOUS VIEW test_int4_to_regtype;
DROP CONTINUOUS VIEW test_oid_to_regconfig;
DROP CONTINUOUS VIEW test_int8_to_regconfig;
DROP CONTINUOUS VIEW test_int2_to_regconfig;
DROP CONTINUOUS VIEW test_int4_to_regconfig;
DROP CONTINUOUS VIEW test_oid_to_regdictionary;
DROP CONTINUOUS VIEW test_int8_to_regdictionary;
DROP CONTINUOUS VIEW test_int2_to_regdictionary;
DROP CONTINUOUS VIEW test_int4_to_regdictionary;
DROP CONTINUOUS VIEW test_text_to_regclass;
DROP CONTINUOUS VIEW test_varchar_to_regclass;
DROP CONTINUOUS VIEW test_text_to_bpchar;
DROP CONTINUOUS VIEW test_text_to_varchar;
DROP CONTINUOUS VIEW test_varchar_to_text;
DROP CONTINUOUS VIEW test_varchar_to_bpchar;
DROP CONTINUOUS VIEW test_char_to_text;
